// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AllMethodsService is the predicate function for allmethodsservice builders.
type AllMethodsService func(*sql.Selector)

// BlogPost is the predicate function for blogpost builders.
type BlogPost func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// DependsOnSkipped is the predicate function for dependsonskipped builders.
type DependsOnSkipped func(*sql.Selector)

// DuplicateNumberMessage is the predicate function for duplicatenumbermessage builders.
type DuplicateNumberMessage func(*sql.Selector)

// EnumWithConflictingValue is the predicate function for enumwithconflictingvalue builders.
type EnumWithConflictingValue func(*sql.Selector)

// ExplicitSkippedMessage is the predicate function for explicitskippedmessage builders.
type ExplicitSkippedMessage func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// ImplicitSkippedMessage is the predicate function for implicitskippedmessage builders.
type ImplicitSkippedMessage func(*sql.Selector)

// InvalidFieldMessage is the predicate function for invalidfieldmessage builders.
type InvalidFieldMessage func(*sql.Selector)

// MessageWithEnum is the predicate function for messagewithenum builders.
type MessageWithEnum func(*sql.Selector)

// MessageWithFieldOne is the predicate function for messagewithfieldone builders.
type MessageWithFieldOne func(*sql.Selector)

// MessageWithID is the predicate function for messagewithid builders.
type MessageWithID func(*sql.Selector)

// MessageWithInts is the predicate function for messagewithints builders.
type MessageWithInts func(*sql.Selector)

// MessageWithOptionals is the predicate function for messagewithoptionals builders.
type MessageWithOptionals func(*sql.Selector)

// MessageWithPackageName is the predicate function for messagewithpackagename builders.
type MessageWithPackageName func(*sql.Selector)

// MessageWithStrings is the predicate function for messagewithstrings builders.
type MessageWithStrings func(*sql.Selector)

// NoBackref is the predicate function for nobackref builders.
type NoBackref func(*sql.Selector)

// OneMethodService is the predicate function for onemethodservice builders.
type OneMethodService func(*sql.Selector)

// Portal is the predicate function for portal builders.
type Portal func(*sql.Selector)

// SkipEdgeExample is the predicate function for skipedgeexample builders.
type SkipEdgeExample func(*sql.Selector)

// TwoMethodService is the predicate function for twomethodservice builders.
type TwoMethodService func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// ValidMessage is the predicate function for validmessage builders.
type ValidMessage func(*sql.Selector)
