// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package internal

const IncrementStarts = "{\"bill_products\":0,\"categories\":4294967296,\"friendships\":8589934592,\"groups\":12884901888,\"one_to_manies\":17179869184,\"projects\":21474836480,\"todos\":25769803776,\"users\":30064771072,\"very_secrets\":34359738368,\"workspaces\":38654705664}"
