// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package internal

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"
	"time"

	// Guardrail: internal model package must remain import-cycle safe and must not import
	// generated root query/client packages (alias direction is root -> internal only).
	"entgo.io/contrib/entgql/internal/todoglobalid/ent/schema/customstruct"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Todo is the model entity for the Todo schema.

type Todo struct {
	Config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Status holds the value of the "status" field.
	Status TodoStatus `json:"status,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Blob holds the value of the "blob" field.
	Blob []byte `json:"blob,omitempty"`
	// CategoryID holds the value of the "category_id" field.
	CategoryID int `json:"category_id,omitempty"`
	// Init holds the value of the "init" field.
	Init map[string]interface{} `json:"init,omitempty"`
	// Custom holds the value of the "custom" field.
	Custom []customstruct.Custom `json:"custom,omitempty"`
	// Customp holds the value of the "customp" field.
	Customp []*customstruct.Custom `json:"customp,omitempty"`
	// Value holds the value of the "value" field.
	Value int `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TodoQuery when eager-loading is set.
	Edges         TodoEdges `json:"edges"`
	project_todos *int
	todo_children *int
	todo_secret   *int
	selectValues  sql.SelectValues
}

// TodoEdges holds the relations/edges for other nodes in the graph.
type TodoEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Todo `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Todo `json:"children,omitempty"`
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// Secret holds the value of the secret edge.
	Secret *VerySecret `json:"secret,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// TotalCount holds the count of the edges above.
	TotalCount [3]map[string]int

	namedChildren map[string][]*Todo
}

// SetLoadedTypes sets the loaded types state for eager-loading.
func (e *TodoEdges) SetLoadedTypes(lt [4]bool) {
	e.loadedTypes = lt
}

// IsLoaded returns whether the edge at the given index was loaded.
func (e TodoEdges) IsLoaded(idx int) bool {
	return e.loadedTypes[idx]
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TodoEdges) ParentOrErr() (*Todo, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{Label: "Todo"}
	}
	return nil, &NotLoadedError{Edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e TodoEdges) ChildrenOrErr() ([]*Todo, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{Edge: "children"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TodoEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{Label: "Category"}
	}
	return nil, &NotLoadedError{Edge: "category"}
}

// SecretOrErr returns the Secret value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TodoEdges) SecretOrErr() (*VerySecret, error) {
	if e.Secret != nil {
		return e.Secret, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{Label: "VerySecret"}
	}
	return nil, &NotLoadedError{Edge: "secret"}
}

// TodoStatus defines the type for the "status" enum field.
type TodoStatus string

func (s TodoStatus) String() string {
	return string(s)
}

// ScanValues returns the types for scanning values from sql.Rows.
func (*Todo) ScanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case "blob", "init", "custom", "customp":
			values[i] = new([]byte)
		case "id", "priority", "category_id", "value":
			values[i] = new(sql.NullInt64)
		case "status", "text":
			values[i] = new(sql.NullString)
		case "created_at":
			values[i] = new(sql.NullTime)
		case "project_todos": // project_todos
			values[i] = new(sql.NullInt64)
		case "todo_children": // todo_children
			values[i] = new(sql.NullInt64)
		case "todo_secret": // todo_secret
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// AssignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Todo fields.
func (_m *Todo) AssignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case "id":
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case "created_at":
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case "status":
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = TodoStatus(value.String)
			}
		case "priority":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case "text":
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case "blob":
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field blob", values[i])
			} else if value != nil {
				_m.Blob = *value
			}
		case "category_id":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = int(value.Int64)
			}
		case "init":
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field init", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Init); err != nil {
					return fmt.Errorf("unmarshal field init: %w", err)
				}
			}
		case "custom":
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field custom", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Custom); err != nil {
					return fmt.Errorf("unmarshal field custom: %w", err)
				}
			}
		case "customp":
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field customp", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Customp); err != nil {
					return fmt.Errorf("unmarshal field customp: %w", err)
				}
			}
		case "value":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = int(value.Int64)
			}
		case "project_todos":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_todos", value)
			} else if value.Valid {
				_m.project_todos = new(int)
				*_m.project_todos = int(value.Int64)
			}
		case "todo_children":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field todo_children", value)
			} else if value.Valid {
				_m.todo_children = new(int)
				*_m.todo_children = int(value.Int64)
			}
		case "todo_secret":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field todo_secret", value)
			} else if value.Valid {
				_m.todo_secret = new(int)
				*_m.todo_secret = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the Todo.
// This includes values selected through modifiers, order, etc.
func (_m *Todo) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// SetProjectTodos sets the project_todos foreign key.
func (_m *Todo) SetProjectTodos(v int) {
	_m.project_todos = &v
}

// GetProjectTodos returns the project_todos foreign key value.
func (_m *Todo) GetProjectTodos() *int {
	return _m.project_todos
}

// SetTodoChildren sets the todo_children foreign key.
func (_m *Todo) SetTodoChildren(v int) {
	_m.todo_children = &v
}

// GetTodoChildren returns the todo_children foreign key value.
func (_m *Todo) GetTodoChildren() *int {
	return _m.todo_children
}

// SetTodoSecret sets the todo_secret foreign key.
func (_m *Todo) SetTodoSecret(v int) {
	_m.todo_secret = &v
}

// GetTodoSecret returns the todo_secret foreign key value.
func (_m *Todo) GetTodoSecret() *int {
	return _m.todo_secret
}

// Unwrap unwraps the Todo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Todo) Unwrap() *Todo {
	unwrapper, ok := _m.Config.Drv.(DriverUnwrapper)
	if !ok {
		panic("internal: Todo is not a transactional entity")
	}
	_m.Config.Drv = unwrapper.UnwrapDriver()
	return _m
}

// String implements the fmt.Stringer.
func (_m *Todo) String() string {
	var builder strings.Builder
	builder.WriteString("Todo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("blob=")
	builder.WriteString(fmt.Sprintf("%v", _m.Blob))
	builder.WriteString(", ")
	builder.WriteString("category_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CategoryID))
	builder.WriteString(", ")
	builder.WriteString("init=")
	builder.WriteString(fmt.Sprintf("%v", _m.Init))
	builder.WriteString(", ")
	builder.WriteString("custom=")
	builder.WriteString(fmt.Sprintf("%v", _m.Custom))
	builder.WriteString(", ")
	builder.WriteString("customp=")
	builder.WriteString(fmt.Sprintf("%v", _m.Customp))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteByte(')')
	return builder.String()
}

// MarshalGQL implements graphql.Marshaler interface.
func (e TodoStatus) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *TodoStatus) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = TodoStatus(str)
	switch str {
	case "IN_PROGRESS", "COMPLETED", "PENDING":
		return nil
	default:
		return fmt.Errorf("%s is not a valid TodoStatus", str)
	}
}

// IsNode implements the Node interface check for GQLGen.
func (*Todo) IsNode() {}

// NamedChildren returns the Children named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Todo) NamedChildren(name string) ([]*Todo, error) {
	if _m.Edges.namedChildren == nil {
		return nil, &NotLoadedError{Edge: name}
	}
	nodes, ok := _m.Edges.namedChildren[name]
	if !ok {
		return nil, &NotLoadedError{Edge: name}
	}
	return nodes, nil
}

func (_m *Todo) AppendNamedChildren(name string, edges ...*Todo) {
	if _m.Edges.namedChildren == nil {
		_m.Edges.namedChildren = make(map[string][]*Todo)
	}
	if len(edges) == 0 {
		_m.Edges.namedChildren[name] = []*Todo{}
	} else {
		_m.Edges.namedChildren[name] = append(_m.Edges.namedChildren[name], edges...)
	}
}

// Todos is a parsable slice of Todo.
type Todos []*Todo
