// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/contrib/entgql/internal/todo/ent/billproduct"
	"github.com/99designs/gqlgen/graphql"
)

var billproductImplementors = []string{"BillProduct", "Node"}

func init() {
	registerNodeResolver(billproduct.Table, nodeResolver{
		byID:  billproductNoder,
		byIDs: billproductNoders,
	})
}

func billproductNoder(ctx context.Context, c *Client, id int) (Noder, error) {
	query := c.BillProduct.Query().
		Where(billproduct.ID(id))
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		if err := query.collectField(ctx, true, graphql.GetOperationContext(ctx), fc.Field, nil, billproductImplementors...); err != nil {
			return nil, err
		}
	}
	return query.Only(ctx)
}

func billproductNoders(ctx context.Context, c *Client, ids []int, idmap map[int][]*Noder) error {
	query := c.BillProduct.Query().
		Where(billproduct.IDIn(ids...))
	query, err := query.CollectFields(ctx, billproductImplementors...)
	if err != nil {
		return err
	}
	nodes, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, node := range nodes {
		for _, noder := range idmap[node.ID] {
			*noder = node
		}
	}
	return nil
}
