// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (c *Category) Todos(
	ctx context.Context, limit *int, offset *int, orderBy *TodoOrder, where *TodoWhereInput,
) (*TodoList, error) {
	opts := []TodoPaginateOption{
		WithTodoOrder(orderBy),
		WithTodoFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := c.Edges.totalCount[0][alias]
	if nodes, err := c.NamedTodos(alias); err == nil || hasTotalCount {
		pager, err := newTodoPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &TodoList{Edges: []*TodoEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return c.QueryTodos().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (c *Category) SubCategories(
	ctx context.Context, limit *int, offset *int, orderBy []*CategoryOrder, where *CategoryWhereInput,
) (*CategoryList, error) {
	opts := []CategoryPaginateOption{
		WithCategoryOrder(orderBy),
		WithCategoryFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := c.Edges.totalCount[1][alias]
	if nodes, err := c.NamedSubCategories(alias); err == nil || hasTotalCount {
		pager, err := newCategoryPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &CategoryList{Edges: []*CategoryEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return c.QuerySubCategories().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (f *Friendship) User(ctx context.Context) (*User, error) {
	result, err := f.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = f.QueryUser().Only(ctx)
	}
	return result, err
}

func (f *Friendship) Friend(ctx context.Context) (*User, error) {
	result, err := f.Edges.FriendOrErr()
	if IsNotLoaded(err) {
		result, err = f.QueryFriend().Only(ctx)
	}
	return result, err
}

func (gr *Group) Users(
	ctx context.Context, limit *int, offset *int, orderBy *UserOrder, where *UserWhereInput,
) (*UserList, error) {
	opts := []UserPaginateOption{
		WithUserOrder(orderBy),
		WithUserFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := gr.Edges.totalCount[0][alias]
	if nodes, err := gr.NamedUsers(alias); err == nil || hasTotalCount {
		pager, err := newUserPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &UserList{Edges: []*UserEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return gr.QueryUsers().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (otm *OneToMany) Parent(ctx context.Context) (*OneToMany, error) {
	result, err := otm.Edges.ParentOrErr()
	if IsNotLoaded(err) {
		result, err = otm.QueryParent().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (otm *OneToMany) Children(ctx context.Context) (result []*OneToMany, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = otm.NamedChildren(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = otm.Edges.ChildrenOrErr()
	}
	if IsNotLoaded(err) {
		result, err = otm.QueryChildren().All(ctx)
	}
	return result, err
}

func (pr *Project) Todos(
	ctx context.Context, limit *int, offset *int, orderBy *TodoOrder, where *TodoWhereInput,
) (*TodoList, error) {
	opts := []TodoPaginateOption{
		WithTodoOrder(orderBy),
		WithTodoFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := pr.Edges.totalCount[0][alias]
	if nodes, err := pr.NamedTodos(alias); err == nil || hasTotalCount {
		pager, err := newTodoPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &TodoList{Edges: []*TodoEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return pr.QueryTodos().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (t *Todo) Parent(ctx context.Context) (*Todo, error) {
	result, err := t.Edges.ParentOrErr()
	if IsNotLoaded(err) {
		result, err = t.QueryParent().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (t *Todo) Children(
	ctx context.Context, limit *int, offset *int, orderBy *TodoOrder, where *TodoWhereInput,
) (*TodoList, error) {
	opts := []TodoPaginateOption{
		WithTodoOrder(orderBy),
		WithTodoFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := t.Edges.totalCount[1][alias]
	if nodes, err := t.NamedChildren(alias); err == nil || hasTotalCount {
		pager, err := newTodoPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &TodoList{Edges: []*TodoEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return t.QueryChildren().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (t *Todo) Category(ctx context.Context) (*Category, error) {
	result, err := t.Edges.CategoryOrErr()
	if IsNotLoaded(err) {
		result, err = t.QueryCategory().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Groups(
	ctx context.Context, limit *int, offset *int, where *GroupWhereInput,
) (*GroupList, error) {
	opts := []GroupPaginateOption{
		WithGroupFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[0][alias]
	if nodes, err := u.NamedGroups(alias); err == nil || hasTotalCount {
		pager, err := newGroupPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &GroupList{Edges: []*GroupEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return u.QueryGroups().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (u *User) Friends(
	ctx context.Context, limit *int, offset *int, orderBy *UserOrder, where *UserWhereInput,
) (*UserList, error) {
	opts := []UserPaginateOption{
		WithUserOrder(orderBy),
		WithUserFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[1][alias]
	if nodes, err := u.NamedFriends(alias); err == nil || hasTotalCount {
		pager, err := newUserPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &UserList{Edges: []*UserEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return u.QueryFriends().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (u *User) Friendships(
	ctx context.Context, limit *int, offset *int, where *FriendshipWhereInput,
) (*FriendshipList, error) {
	opts := []FriendshipPaginateOption{
		WithFriendshipFilter(where.Filter),
	}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[2][alias]
	if nodes, err := u.NamedFriendships(alias); err == nil || hasTotalCount {
		pager, err := newFriendshipPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &FriendshipList{Edges: []*FriendshipEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return u.QueryFriendships().PaginateLimitOffset(ctx, limit, offset, opts...)
}
