// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entgo.io/contrib/entgql/internal/todo/ent/internal"
)

// Model type aliases from internal.
// Guardrail: aliasing is one-way (root -> internal), and methods belong to the type definition site.
// Do not attach root-only methods to alias models; add model methods on internal types instead.
// Keep the internal package free of root query/client imports to avoid import cycles.
type Group = internal.Group
type GroupEdges = internal.GroupEdges
type Groups = internal.Groups
