// Copyright 2019-present Facebook
//
// Licensed x under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"

	"entgo.io/contrib/entgql"
	"entgo.io/contrib/entgql/internal/todogid/ent/post"
	"entgo.io/contrib/entgql/internal/todogid/ent/todo"
	"entgo.io/contrib/entgql/internal/todogid/ent/user"
	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/hashicorp/go-multierror"
)

const (
	typePost = "post"
	typeTodo = "todo"
	typeUser = "user"
)

// GlobalID returns the global identifier for the given Post node.
func (po *Post) GlobalID(context.Context) (string, error) {
	id := fmt.Sprintf("%s:%s", typePost, po.ID)
	return base64.StdEncoding.EncodeToString([]byte(id)), nil
}

// GlobalID returns the global identifier for the given Todo node.
func (t *Todo) GlobalID(context.Context) (string, error) {
	id := fmt.Sprintf("%s:%d", typeTodo, t.ID)
	return base64.StdEncoding.EncodeToString([]byte(id)), nil
}

// GlobalID returns the global identifier for the given User node.
func (u *User) GlobalID(context.Context) (string, error) {
	id := fmt.Sprintf("%s:%d", typeUser, u.ID)
	return base64.StdEncoding.EncodeToString([]byte(id)), nil
}

type ResolvedGlobal struct{ Type, ID string }

func FromGlobalID(s string) (*ResolvedGlobal, error) {
	b, err := base64.URLEncoding.DecodeString(s)
	if err != nil {
		return nil, err
	}
	tid := strings.Split(string(b), ":")
	if len(tid) != 2 {
		return nil, fmt.Errorf("invalid global identifier format %q", b)
	}
	return &ResolvedGlobal{Type: tid[0], ID: tid[1]}, nil
}

func (r *ResolvedGlobal) UUID() (id uuid.UUID, err error) {
	err = id.UnmarshalText([]byte(r.ID))
	return
}
func UUIDFromGlobalID(s string) (id uuid.UUID, _ error) {
	r, err := FromGlobalID(s)
	if err != nil {
		return id, err
	}
	return r.UUID()
}

func (r *ResolvedGlobal) Int() (int, error) {
	return strconv.Atoi(r.ID)
}
func IntFromGlobalID(s string) (int, error) {
	r, err := FromGlobalID(s)
	if err != nil {
		return 0, err
	}
	return r.Int()
}

func (c *Client) FromGlobalID(ctx context.Context, id string) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	r, err := FromGlobalID(id)
	if err != nil {
		return nil, err
	}
	switch r.Type {
	case typePost:
		id, err := r.UUID()
		if err != nil {
			return nil, err
		}
		n, err := c.Post.Query().
			Where(post.ID(id)).
			CollectFields(ctx, "Post").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case typeTodo:
		id, err := r.Int()
		if err != nil {
			return nil, err
		}
		n, err := c.Todo.Query().
			Where(todo.ID(id)).
			CollectFields(ctx, "Todo").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	case typeUser:
		id, err := r.Int()
		if err != nil {
			return nil, err
		}
		n, err := c.User.Query().
			Where(user.ID(id)).
			CollectFields(ctx, "User").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	default:
		return nil, fmt.Errorf("cannot resolve noder of type %q: %w", r.Type, errNodeInvalidID)
	}
}

func (c *Client) FromGlobalIDs(ctx context.Context, ids []string) (_ []Noder, err error) {
	switch len(ids) {
	case 1:
		noder, err := c.FromGlobalID(ctx, ids[0])
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}
	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	types := make(map[string][]*ResolvedGlobal)
	id2idx := make(map[ResolvedGlobal][]int, len(ids))
	for i, id := range ids {
		r, err := FromGlobalID(id)
		if err != nil {
			errors[i] = err
			continue
		}
		types[r.Type] = append(types[r.Type], r)
		id2idx[*r] = append(id2idx[*r], i)
	}

	for typ, ids := range types {
		nodes, err := c.nodes(ctx, typ, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[*id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[*id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) nodes(ctx context.Context, typ string, rs []*ResolvedGlobal) ([]Noder, error) {
	noders := make([]Noder, len(rs))
	switch typ {
	case typePost:
		ids := make([]uuid.UUID, len(rs))
		for i := range ids {
			id, err := rs[i].UUID()
			if err != nil {
				return nil, err
			}
			ids[i] = id
		}
		idmap := make(map[uuid.UUID][]*Noder, len(ids))
		for i, id := range ids {
			idmap[id] = append(idmap[id], &noders[i])
		}
		nodes, err := c.Post.Query().
			Where(post.IDIn(ids...)).
			CollectFields(ctx, "Post").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case typeTodo:
		ids := make([]int, len(rs))
		for i := range ids {
			id, err := rs[i].Int()
			if err != nil {
				return nil, err
			}
			ids[i] = id
		}
		idmap := make(map[int][]*Noder, len(ids))
		for i, id := range ids {
			idmap[id] = append(idmap[id], &noders[i])
		}
		nodes, err := c.Todo.Query().
			Where(todo.IDIn(ids...)).
			CollectFields(ctx, "Todo").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	case typeUser:
		ids := make([]int, len(rs))
		for i := range ids {
			id, err := rs[i].Int()
			if err != nil {
				return nil, err
			}
			ids[i] = id
		}
		idmap := make(map[int][]*Noder, len(ids))
		for i, id := range ids {
			idmap[id] = append(idmap[id], &noders[i])
		}
		nodes, err := c.User.Query().
			Where(user.IDIn(ids...)).
			CollectFields(ctx, "User").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from type %q: %w", typ, errNodeInvalidID)
	}
	return noders, nil
}
