// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/contrib/entproto/internal/entprototest/ent/messagewithphpnamespace"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageWithPhpNamespaceCreate is the builder for creating a MessageWithPhpNamespace entity.
type MessageWithPhpNamespaceCreate struct {
	config
	mutation *MessageWithPhpNamespaceMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (mwpnc *MessageWithPhpNamespaceCreate) SetName(s string) *MessageWithPhpNamespaceCreate {
	mwpnc.mutation.SetName(s)
	return mwpnc
}

// Mutation returns the MessageWithPhpNamespaceMutation object of the builder.
func (mwpnc *MessageWithPhpNamespaceCreate) Mutation() *MessageWithPhpNamespaceMutation {
	return mwpnc.mutation
}

// Save creates the MessageWithPhpNamespace in the database.
func (mwpnc *MessageWithPhpNamespaceCreate) Save(ctx context.Context) (*MessageWithPhpNamespace, error) {
	return withHooks(ctx, mwpnc.sqlSave, mwpnc.mutation, mwpnc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mwpnc *MessageWithPhpNamespaceCreate) SaveX(ctx context.Context) *MessageWithPhpNamespace {
	v, err := mwpnc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mwpnc *MessageWithPhpNamespaceCreate) Exec(ctx context.Context) error {
	_, err := mwpnc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mwpnc *MessageWithPhpNamespaceCreate) ExecX(ctx context.Context) {
	if err := mwpnc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mwpnc *MessageWithPhpNamespaceCreate) check() error {
	if _, ok := mwpnc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MessageWithPhpNamespace.name"`)}
	}
	return nil
}

func (mwpnc *MessageWithPhpNamespaceCreate) sqlSave(ctx context.Context) (*MessageWithPhpNamespace, error) {
	if err := mwpnc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mwpnc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mwpnc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mwpnc.mutation.id = &_node.ID
	mwpnc.mutation.done = true
	return _node, nil
}

func (mwpnc *MessageWithPhpNamespaceCreate) createSpec() (*MessageWithPhpNamespace, *sqlgraph.CreateSpec) {
	var (
		_node = &MessageWithPhpNamespace{config: mwpnc.config}
		_spec = sqlgraph.NewCreateSpec(messagewithphpnamespace.Table, sqlgraph.NewFieldSpec(messagewithphpnamespace.FieldID, field.TypeInt))
	)
	if value, ok := mwpnc.mutation.Name(); ok {
		_spec.SetField(messagewithphpnamespace.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// MessageWithPhpNamespaceCreateBulk is the builder for creating many MessageWithPhpNamespace entities in bulk.
type MessageWithPhpNamespaceCreateBulk struct {
	config
	err      error
	builders []*MessageWithPhpNamespaceCreate
}

// Save creates the MessageWithPhpNamespace entities in the database.
func (mwpncb *MessageWithPhpNamespaceCreateBulk) Save(ctx context.Context) ([]*MessageWithPhpNamespace, error) {
	if mwpncb.err != nil {
		return nil, mwpncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mwpncb.builders))
	nodes := make([]*MessageWithPhpNamespace, len(mwpncb.builders))
	mutators := make([]Mutator, len(mwpncb.builders))
	for i := range mwpncb.builders {
		func(i int, root context.Context) {
			builder := mwpncb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageWithPhpNamespaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mwpncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mwpncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mwpncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mwpncb *MessageWithPhpNamespaceCreateBulk) SaveX(ctx context.Context) []*MessageWithPhpNamespace {
	v, err := mwpncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mwpncb *MessageWithPhpNamespaceCreateBulk) Exec(ctx context.Context) error {
	_, err := mwpncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mwpncb *MessageWithPhpNamespaceCreateBulk) ExecX(ctx context.Context) {
	if err := mwpncb.Exec(ctx); err != nil {
		panic(err)
	}
}
