// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/contrib/entproto/internal/entprototest/ent/onemethodservice"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OneMethodService is the model entity for the OneMethodService schema.
type OneMethodService struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OneMethodService) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case onemethodservice.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OneMethodService fields.
func (oms *OneMethodService) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case onemethodservice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			oms.ID = int(value.Int64)
		default:
			oms.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OneMethodService.
// This includes values selected through modifiers, order, etc.
func (oms *OneMethodService) Value(name string) (ent.Value, error) {
	return oms.selectValues.Get(name)
}

// Update returns a builder for updating this OneMethodService.
// Note that you need to call OneMethodService.Unwrap() before calling this method if this OneMethodService
// was returned from a transaction, and the transaction was committed or rolled back.
func (oms *OneMethodService) Update() *OneMethodServiceUpdateOne {
	return NewOneMethodServiceClient(oms.config).UpdateOne(oms)
}

// Unwrap unwraps the OneMethodService entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (oms *OneMethodService) Unwrap() *OneMethodService {
	_tx, ok := oms.config.driver.(*txDriver)
	if !ok {
		panic("ent: OneMethodService is not a transactional entity")
	}
	oms.config.driver = _tx.drv
	return oms
}

// String implements the fmt.Stringer.
func (oms *OneMethodService) String() string {
	var builder strings.Builder
	builder.WriteString("OneMethodService(")
	builder.WriteString(fmt.Sprintf("id=%v", oms.ID))
	builder.WriteByte(')')
	return builder.String()
}

// OneMethodServices is a parsable slice of OneMethodService.
type OneMethodServices []*OneMethodService
