// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package todopulid

import (
	"time"

	"entgo.io/contrib/entgql/internal/todopulid/ent/schema/pulid"
)

// UpdateFriendshipInput is used for update Friendship object.
// Input was generated by ent.
type UpdateFriendshipInput struct {
	CreatedAt *time.Time `json:"createdAt"`
	UserID    *pulid.ID  `json:"userID"`
	FriendID  *pulid.ID  `json:"friendID"`
}
