// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/contrib/entproto/internal/todo/ent/multiwordschema"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MultiWordSchemaCreate is the builder for creating a MultiWordSchema entity.
type MultiWordSchemaCreate struct {
	config
	mutation *MultiWordSchemaMutation
	hooks    []Hook
}

// SetUnit sets the "unit" field.
func (mwsc *MultiWordSchemaCreate) SetUnit(m multiwordschema.Unit) *MultiWordSchemaCreate {
	mwsc.mutation.SetUnit(m)
	return mwsc
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (mwsc *MultiWordSchemaCreate) SetNillableUnit(m *multiwordschema.Unit) *MultiWordSchemaCreate {
	if m != nil {
		mwsc.SetUnit(*m)
	}
	return mwsc
}

// Mutation returns the MultiWordSchemaMutation object of the builder.
func (mwsc *MultiWordSchemaCreate) Mutation() *MultiWordSchemaMutation {
	return mwsc.mutation
}

// Save creates the MultiWordSchema in the database.
func (mwsc *MultiWordSchemaCreate) Save(ctx context.Context) (*MultiWordSchema, error) {
	mwsc.defaults()
	return withHooks(ctx, mwsc.sqlSave, mwsc.mutation, mwsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mwsc *MultiWordSchemaCreate) SaveX(ctx context.Context) *MultiWordSchema {
	v, err := mwsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mwsc *MultiWordSchemaCreate) Exec(ctx context.Context) error {
	_, err := mwsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mwsc *MultiWordSchemaCreate) ExecX(ctx context.Context) {
	if err := mwsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mwsc *MultiWordSchemaCreate) defaults() {
	if _, ok := mwsc.mutation.Unit(); !ok {
		v := multiwordschema.DefaultUnit
		mwsc.mutation.SetUnit(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mwsc *MultiWordSchemaCreate) check() error {
	if _, ok := mwsc.mutation.Unit(); !ok {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required field "MultiWordSchema.unit"`)}
	}
	if v, ok := mwsc.mutation.Unit(); ok {
		if err := multiwordschema.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "MultiWordSchema.unit": %w`, err)}
		}
	}
	return nil
}

func (mwsc *MultiWordSchemaCreate) sqlSave(ctx context.Context) (*MultiWordSchema, error) {
	if err := mwsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mwsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mwsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mwsc.mutation.id = &_node.ID
	mwsc.mutation.done = true
	return _node, nil
}

func (mwsc *MultiWordSchemaCreate) createSpec() (*MultiWordSchema, *sqlgraph.CreateSpec) {
	var (
		_node = &MultiWordSchema{config: mwsc.config}
		_spec = sqlgraph.NewCreateSpec(multiwordschema.Table, sqlgraph.NewFieldSpec(multiwordschema.FieldID, field.TypeInt))
	)
	if value, ok := mwsc.mutation.Unit(); ok {
		_spec.SetField(multiwordschema.FieldUnit, field.TypeEnum, value)
		_node.Unit = value
	}
	return _node, _spec
}

// MultiWordSchemaCreateBulk is the builder for creating many MultiWordSchema entities in bulk.
type MultiWordSchemaCreateBulk struct {
	config
	err      error
	builders []*MultiWordSchemaCreate
}

// Save creates the MultiWordSchema entities in the database.
func (mwscb *MultiWordSchemaCreateBulk) Save(ctx context.Context) ([]*MultiWordSchema, error) {
	if mwscb.err != nil {
		return nil, mwscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mwscb.builders))
	nodes := make([]*MultiWordSchema, len(mwscb.builders))
	mutators := make([]Mutator, len(mwscb.builders))
	for i := range mwscb.builders {
		func(i int, root context.Context) {
			builder := mwscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MultiWordSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mwscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mwscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mwscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mwscb *MultiWordSchemaCreateBulk) SaveX(ctx context.Context) []*MultiWordSchema {
	v, err := mwscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mwscb *MultiWordSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := mwscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mwscb *MultiWordSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := mwscb.Exec(ctx); err != nil {
		panic(err)
	}
}
