// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entgo.io/contrib/entgql/internal/todoglobalid/ent/runtime.go

const (
	Version = "v0.14.2-0.20250116103911-b91f8daf0e32"           // Version of ent codegen.
	Sum     = "h1:caGPxY54QfxAj6W9Msw3vgOPDved92NoZjHXYiTRFHI=" // Sum of ent codegen.
)
