// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	driver "database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// TxOpener is an autogenerated mock type for the TxOpener type
type TxOpener struct {
	mock.Mock
}

// OpenTx provides a mock function with given fields: ctx
func (_m *TxOpener) OpenTx(ctx context.Context) (context.Context, driver.Tx, error) {
	ret := _m.Called(ctx)

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	var r1 driver.Tx
	if rf, ok := ret.Get(1).(func(context.Context) driver.Tx); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(driver.Tx)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
